import type {Metadata} from "next";
import "./globals.css";
import {Header} from "@/compontnts/Header";

export const metadata: Metadata = {
    title: "Candles shop",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`antialiased`}
        >

        <Header/>

        <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
            {children}
        </main>

        </body>
        </html>
    );
}
